### ISSUE TITLE
not logged-in user allowed to play game

### ISSUE THREAD

**Issue by jonboy042** [EliW09/tic-tac-toe-client#1]
Steps:
1) click sign in
2) enter unregistered email and fake password - screen displays login error
3) click "new game" and start playing

Step #2 scenarios:
- un-registered email and password
- empty password
- both fields empty

Expected behavior -
 If not logged in New Game button should be either disabled or not-present
Actual behavior - 
 New Game button functions and allows you to start game.

**Comment by jonboy042** [comment]
Leaving email and pass fields blank creates same scenerio

**Comment by EliW09** [comment]
Fixed. Had Jquery showing the game even on failure
